Traceback (most recent call last):
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/Etienne/PycharmProjects/localBook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sim_dt = 0.1         # simulation step (10 Hz)
env = DroneLandingEnv(render_mode=None, dt=sim_dt)
controller_dt = 0.1  # controller step (1 Hz)

pid = PIDController(Kp=[2.0,2.0,2.0, 2.0], Ki=[0.0,0.0,0.0,0.0], Kd=[0.0,0.0,0.0,0.0], dt=controller_dt, integral_limit=0.5, z_fixed_speed= -0.2)

states, target = run_pid_simulation(env = env, pid = pid, init_mode='fixed', plot=True, init_pos = [2.0,2.0,2.0,2.0])
------------------


[31m---------------------------------------------------------------------------[39m
[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[5][39m[32m, line 7[39m
[32m      3[39m controller_dt = [32m0.1[39m  [38;5;66;03m# controller step (1 Hz)[39;00m
[32m      5[39m pid = PIDController(Kp=[[32m2.0[39m,[32m2.0[39m,[32m2.0[39m, [32m2.0[39m], Ki=[[32m0.0[39m,[32m0.0[39m,[32m0.0[39m,[32m0.0[39m], Kd=[[32m0.0[39m,[32m0.0[39m,[32m0.0[39m,[32m0.0[39m], dt=controller_dt, integral_limit=[32m0.5[39m, z_fixed_speed= -[32m0.2[39m)
[32m----> [39m[32m7[39m states, target = run_pid_simulation(env = env, pid = pid, init_mode=[33m'[39m[33mfixed[39m[33m'[39m, plot=[38;5;28;01mTrue[39;00m, init_pos = [[32m2.0[39m,[32m2.0[39m,[32m2.0[39m,[32m2.0[39m])

[31mValueError[39m: too many values to unpack (expected 2)

